### ISSUE TITLE
[Bug] If token unaligned with Grid, doesn't push

### ISSUE THREAD

**Issue by Shuggaloaf** [oOve/pushable#1]
As you can see in the GIF below any token not aligned with a grid square will not be able to be pushed. All crates you see are tokens setup to be pushable. 

![Capture-01(1)](https://user-images.githubusercontent.com/79543184/159762308-1fae8221-1abd-457f-9154-69c835d22d77.gif)

No errors. Specs below..
FVTT v9.255
DnD5e V 1.5.7
Chrome & Electron

&nbsp;

Unrelated, but also wanted to check before opening a ticket: I noticed that when the prototype token is setup as pushable that it does not carry over to tokens dragged onto the board. I have a feeling this is due to a limitation with IDs or some such rather than a bug. If that is not the case though then let me know and I will open another ticket for that as well. 

Thanks!

**Comment by oOve** [comment]
This is an easy fix :)
Why the prototype setup not carrying over I'm not sure. I'll investigate a bit.

**Comment by Shuggaloaf** [comment]
>This is an easy fix :)

Great!

>Why the prototype setup not carrying over I'm not sure. I'll investigate a bit.

Oh so it was supposed to carry over. That's very convenient for setting up a compendium of pushables to just drag out. Hope this one is an easy fix for you too!

**Comment by oOve** [comment]
Question. 
What should the default behavior be when pushing non-aligned tokens?
Push them, so they end up un-aligned?
Push more than one, since one can push two and so on?
I'm honestly tempted to introduce physics based pushing, in that you push something straight ahead, but what you push's center of gravity is off to the side, you'll push the box ~45 degree to the side and not straight ahead.

**Comment by oOve** [comment]
Should be fixed now

**Comment by Shuggaloaf** [comment]
>Should be fixed now

Couldn't wait for me to respond huh? Haha just joking, will never complain about a quick fix! 

To give you some feedback on your questions, first, I think the physics based idea would be really cool. I'm not a coder so I don't know but I would just be concerned if it affected performance. If not and it's easy enough for you to do, I'd definitely +1 that feature. 

As far as alignment, I'm not sure what you went with but I'd probably leave them unaligned. I could see people wanting them to snap to grid but then my thought is they would have probably placed them within a grid cell in the first place. 

I would keep the behavior of one pushing another and so on. Although as I mentioned in my other suggestion, I really think some kind of user-enabled/set limiter is needed. 

I'll try out the update now and check back. Thanks for your effort!

**Comment by Shuggaloaf** [comment]
Not seeing a new release. Will check back later or tomorrow. Thanks again.

**Comment by oOve** [comment]
I will most likely push an update tomorrow.
I went with alignment in the direction of push, but left it un-aligned in the non-pushed direction.
I'll leave the physics based directions for a feature request option instead of a bug. :)

**Comment by oOve** [comment]
I'll close this issue first after I push the new release.

**Comment by oOve** [comment]
Fixed as of release 1.0.3.
