### ISSUE TITLE
Collision.

### ISSUE THREAD

**Issue by Akallabeth13666** [oOve/pushable#14]
Hi,

Shouldn't this option:
![option](https://user-images.githubusercontent.com/95130435/173115362-a44784d6-133c-4c2f-9d9e-1148cc4d0c56.JPG)

Prevent this:

![collision](https://user-images.githubusercontent.com/95130435/173115426-412a23e5-1c82-4de8-8a59-17d0da3680e3.JPG)

Or am I misunderstanding that?

**Comment by Akallabeth13666** [comment]
Sorry, got it working. But pulling is still not working when I am pushing the P button. Any idea what might be wrong?

**Comment by oOve** [comment]
Have you checked what its bound to?
![image](https://user-images.githubusercontent.com/8543541/173154742-c7f34634-2e35-4ec9-a635-66aa499a4cc0.png)

**Comment by Akallabeth13666** [comment]
Ok, it works, actually it was fault of my keyboard :/ I have different profiles that change keys to be bound to different keys depending on launched application. It decided not switch to proper profile :/

Sorry for bothering you :)
Great work btw! :)
