### ISSUE TITLE
v10 compatibility? 

### ISSUE THREAD

**Issue by nirurin** [oOve/pushable#15]
As this module seems to not have had any updates for a while, and there's no message regarding whether it's being worked on for v10, I thought I would ask the question.

**Comment by oOve** [comment]
I maintain a list over my v10 progress on my discord channel. 
https://discord.com/channels/798236970992009237/1005493664375644241

pushable is sadly still in the red, but will be ported, thank you for your interest :)

**Comment by oOve** [comment]
https://github.com/oOve/pushable/releases/tag/10.0.1 is released, featuring v10 support. Closing issue.
