### ISSUE TITLE
[Feature] Pull

### ISSUE THREAD

**Issue by brunocalado** [oOve/pushable#2]
Hi. Great Job! This module is amazing! Thank you very much!!!

I'm having fun already.
https://user-images.githubusercontent.com/4999783/159763503-8a7011ca-4bfe-498e-85cf-caef4b0bfae0.mp4

Can you add a pull option? Example: The player press shift and moves away from the crate. The crate is then dragged with him

**Comment by oOve** [comment]
Haha.. Nice. Looks amazingly old school. 
I'll look into the pulling.

**Comment by brunocalado** [comment]
> Haha.. Nice. Looks amazingly old school. I'll look into the pulling.

It's the 8bit movement module

**Comment by Shuggaloaf** [comment]
Came here to suggest this as well. Pull would be great, especially for when the players inevitably push something into a wall/corner. Could also be useful for pulling out wall blocks, book cases, etc. to unhide secret passages. Probably a couple dozen other uses as well. 

+1

**Comment by oOve** [comment]
Pulling implemented in version 1.0.3
Default key P to hold down while moving away from a pushable token
