### ISSUE TITLE
[BUG] Token Pass Through to Crate

### ISSUE THREAD

**Issue by brunocalado** [oOve/pushable#4]
The token is passing Through to Crate. This is player view.

I need to pass and pass again to be able to push.

https://user-images.githubusercontent.com/4999783/160011685-c8c9cec8-6e1f-465a-a721-5f546461345b.mp4

**Comment by oOve** [comment]
Should be fixed now

**Comment by brunocalado** [comment]
It's not working well yet.
https://user-images.githubusercontent.com/4999783/160241352-96eeb152-dadb-4fcd-a9cf-50aef42a1688.mp4

**Comment by oOve** [comment]
New release just pushed. Check again. If it works, we can close this ticket :)
