### ISSUE TITLE
[Suggestion] Do not allow pushables to be pushed past/over non-pushable tokens

### ISSUE THREAD

**Issue by Shuggaloaf** [oOve/pushable#6]
Currently if a token is pushing a pushable and encounters another token that is not a pushable token, it just keeps going, basically plowing over the non-pushable token. 

Since most non-pushable tokens are going to be things you don't want to be able to push past- such as PCs, NPCs, vehicles, etc. -I would suggest stopping the movement when a pushable hits a non-pushable token as you currently do when hitting a wall. 

Even if pushing over/past a non-pushable may be rarely desired, I would guess it would be just that - rare, and 99% of the time is not what a GM would want to happen. 

Thanks again!

**Comment by oOve** [comment]
Solution for now is to make your interacting tokens pushable as well.

**Comment by Shuggaloaf** [comment]
But then wouldn't that token be, well, pushable? So if I have a PC that is pushing 2 crates and then hits another PC, that 2nd PC shouldn't be able to be pushed. Likewise the crates shouldn't really push through them either. 

Making them pushable would be OK as a workaround if there was a way to "lock" them to not be able to  be pushed. But then at that point we're just right back to square 1.

**Comment by oOve** [comment]
Issue isn't closed :)
I value your opinion @Shuggaloaf regular tokens will stop them in the next release.

**Comment by Shuggaloaf** [comment]
I got you. I didn't mean to sound like I didn't think you valued my opinion. Sorry if it came off that way! I didn't think I had explained myself clearly so was over-explaining. Sorry for any confusion and definitely don't want to come off as pushy.

**Comment by oOve** [comment]
Fixed as of last version (not released yet)

**Comment by Shuggaloaf** [comment]
Thanks oOve! Looking fwd to it.
