### ISSUE TITLE
[Suggestions] Assets Pack

### ISSUE THREAD

**Issue by brunocalado** [oOve/pushable#9]
Hi

I made a map for learning purposes in my module (MD - Random Stuff). The assets used are free (https://www.kenney.nl/assets/sokoban). Maybe you can add to this module.
![image](https://user-images.githubusercontent.com/4999783/160624605-f07a7c30-ba04-490a-9076-80790f5d6828.png)

Add to readme a list of videos showing off the module. I have one in Brazilian Portuguese (https://www.youtube.com/watch?v=jx7nEoQyOF0)

**Comment by oOve** [comment]
Wow, thank you. I will at earliest opportunity try to add a "language file" as well to this project. Maybe you could help me with the Brazilian Portuguese translation :)

**Comment by brunocalado** [comment]
> Wow, thank you. I will at earliest opportunity try to add a "language file" as well to this project. Maybe you could help me with the Brazilian Portuguese translation :)

Sure. I add this to my modules help translators

**Comment by oOve** [comment]
I added an issue #10 here @brunocalado 
No hurry. Take it when you have time :)

**Comment by oOve** [comment]
I'll close this issue. I added some crates as default assets.
